development: &default
  encoding: utf8
  adapter: postgresql
  min_messages: warning
  timeout: 5000
  url:  <%= "postgres://#{ENV['AACT_DB_SUPER_USERNAME'] || 'ctti'}@#{ENV['APPLICATION_HOST'] || 'localhost'}:5432/#{ENV['AACT_ADMIN_DATABASE_NAME'] || 'aact_admin'}" %>

test:
  encoding: utf8
  adapter: postgresql
  database: aact_admin_test

production: &deploy
  encoding: utf8
  adapter: postgresql
  min_messages: warning
  timeout: 5000
  url:  <%= "postgres://#{ENV['AACT_DB_SUPER_USERNAME'] || 'ctti'}@#{ENV['APPLICATION_HOST'] || 'localhost'}:5432/#{ENV['AACT_ADMIN_DATABASE_NAME'] || 'aact_admin'}" %>
